// NPM
import React from 'react';
import { connect } from 'react-redux';

// Components
import TodoList from './presentational/TodoList';

// Actions
import todoActions from '../actions/todos';

// Filter todos according to chosen filter
const getVisibleTodos = (todos, filter) => {
  switch (filter) {
    case 'SHOW_ALL':
      return todos;
    case 'SHOW_COMPLETED':
      return todos.filter(todo => {
        return todo.completed;
      });
    case 'SHOW_ACTIVE':
      return todos.filter(todo => {
        return !todo.completed;
      });
    default:
      return todos;
  }
};

const mapStateToTodoListProps = (state) => {
  return {
    todos: getVisibleTodos(
      state.todos,
      state.visibilityFilter
    )
  };
};

const mapDispatchToTodoListProps = (dispatch) => {
  return {
    onTodoClick: (id) => {
      dispatch(todoActions.toggleTodo(id));
    }
  };
};

// Todolist container component, generated by ReactRedux with `connect`
const VisibleTodoList = connect(
  mapStateToTodoListProps,
  mapDispatchToTodoListProps
)(TodoList);

export default VisibleTodoList;
